//! Deterministische Produkt-Anreicherung: normalisierte Kategorie + Emoji.
//!
//! Die App zeigt nur die hier definierten Kategorien an (CATEGORIES) — die
//! rohen Scraper-Kategorien der Ketten sind uneinheitlich und bleiben lokal.
//! Emojis kommen aus einer kuratierten Keyword-Tabelle (längstes passendes
//! Keyword gewinnt); ohne Treffer greift das Kategorie-Standard-Emoji.

/// Stabile Kategorienliste — die App hardcodet diese Werte. Änderungen nur
/// bewusst zusammen mit einem App-Update.
pub const CATEGORIES: [&str; 15] = [
    "Obst & Gemüse",
    "Molkerei & Eier",
    "Fleisch & Wurst",
    "Fisch",
    "Backwaren",
    "Tiefkühl",
    "Süßes & Snacks",
    "Getränke",
    "Alkohol",
    "Vorräte & Kochen",
    "Drogerie",
    "Haushalt",
    "Tierbedarf",
    "Kinder",
    "Sonstiges",
];

pub const FALLBACK_CATEGORY: &str = "Sonstiges";

/// Standard-Emoji pro Kategorie — greift, wenn kein Keyword passt.
const CATEGORY_EMOJI: [(&str, &str); 15] = [
    ("Obst & Gemüse", "🥬"),
    ("Molkerei & Eier", "🥛"),
    ("Fleisch & Wurst", "🥩"),
    ("Fisch", "🐟"),
    ("Backwaren", "🥖"),
    ("Tiefkühl", "❄️"),
    ("Süßes & Snacks", "🍬"),
    ("Getränke", "🥤"),
    ("Alkohol", "🍺"),
    ("Vorräte & Kochen", "🥫"),
    ("Drogerie", "🧴"),
    ("Haushalt", "🧽"),
    ("Tierbedarf", "🐾"),
    ("Kinder", "🧸"),
    ("Sonstiges", "🛒"),
];

pub fn default_emoji(category: &str) -> &'static str {
    CATEGORY_EMOJI
        .iter()
        .find(|(c, _)| *c == category)
        .map(|(_, e)| *e)
        .unwrap_or("🛒")
}

/// Keyword → (Emoji, Kategorie). Substring-Match auf lowercased
/// Titel+Untertitel; das längste passende Keyword gewinnt, dadurch schlägt
/// z. B. "apfelschorle" (Getränke) das enthaltene "apfel" (Obst).
const RULES: &[(&str, &str, &str)] = &[
    // Obst
    ("apfel", "🍎", "Obst & Gemüse"),
    ("äpfel", "🍎", "Obst & Gemüse"),
    ("banane", "🍌", "Obst & Gemüse"),
    ("erdbeer", "🍓", "Obst & Gemüse"),
    ("himbeer", "🫐", "Obst & Gemüse"),
    ("heidelbeer", "🫐", "Obst & Gemüse"),
    ("blaubeer", "🫐", "Obst & Gemüse"),
    ("traube", "🍇", "Obst & Gemüse"),
    ("zitrone", "🍋", "Obst & Gemüse"),
    ("limette", "🍋", "Obst & Gemüse"),
    ("orange", "🍊", "Obst & Gemüse"),
    ("mandarine", "🍊", "Obst & Gemüse"),
    ("clementine", "🍊", "Obst & Gemüse"),
    ("pfirsich", "🍑", "Obst & Gemüse"),
    ("nektarine", "🍑", "Obst & Gemüse"),
    ("aprikose", "🍑", "Obst & Gemüse"),
    ("kirsche", "🍒", "Obst & Gemüse"),
    ("melone", "🍈", "Obst & Gemüse"),
    ("wassermelone", "🍉", "Obst & Gemüse"),
    ("ananas", "🍍", "Obst & Gemüse"),
    ("mango", "🥭", "Obst & Gemüse"),
    ("kiwi", "🥝", "Obst & Gemüse"),
    ("birne", "🍐", "Obst & Gemüse"),
    ("pflaume", "🟣", "Obst & Gemüse"),
    ("avocado", "🥑", "Obst & Gemüse"),
    // Gemüse
    ("tomate", "🍅", "Obst & Gemüse"),
    ("gurke", "🥒", "Obst & Gemüse"),
    ("zucchini", "🥒", "Obst & Gemüse"),
    ("paprika", "🫑", "Obst & Gemüse"),
    ("möhre", "🥕", "Obst & Gemüse"),
    ("karotte", "🥕", "Obst & Gemüse"),
    ("kartoffel", "🥔", "Obst & Gemüse"),
    ("zwiebel", "🧅", "Obst & Gemüse"),
    ("knoblauch", "🧄", "Obst & Gemüse"),
    ("brokkoli", "🥦", "Obst & Gemüse"),
    ("blumenkohl", "🥦", "Obst & Gemüse"),
    ("salat", "🥬", "Obst & Gemüse"),
    ("spinat", "🥬", "Obst & Gemüse"),
    ("kohlrabi", "🥬", "Obst & Gemüse"),
    ("spargel", "🌱", "Obst & Gemüse"),
    ("pilze", "🍄", "Obst & Gemüse"),
    ("champignon", "🍄", "Obst & Gemüse"),
    ("aubergine", "🍆", "Obst & Gemüse"),
    ("mais", "🌽", "Obst & Gemüse"),
    ("kürbis", "🎃", "Obst & Gemüse"),
    ("radieschen", "🌶️", "Obst & Gemüse"),
    ("ingwer", "🫚", "Obst & Gemüse"),
    // Molkerei & Eier
    ("milch", "🥛", "Molkerei & Eier"),
    ("joghurt", "🥛", "Molkerei & Eier"),
    ("jogurt", "🥛", "Molkerei & Eier"),
    ("quark", "🥛", "Molkerei & Eier"),
    ("sahne", "🥛", "Molkerei & Eier"),
    ("butter", "🧈", "Molkerei & Eier"),
    ("margarine", "🧈", "Molkerei & Eier"),
    ("käse", "🧀", "Molkerei & Eier"),
    ("gouda", "🧀", "Molkerei & Eier"),
    ("mozzarella", "🧀", "Molkerei & Eier"),
    ("feta", "🧀", "Molkerei & Eier"),
    ("eier", "🥚", "Molkerei & Eier"),
    ("skyr", "🥛", "Molkerei & Eier"),
    // Fleisch & Wurst
    ("hähnchen", "🍗", "Fleisch & Wurst"),
    ("hühner", "🍗", "Fleisch & Wurst"),
    ("pute", "🍗", "Fleisch & Wurst"),
    ("schwein", "🥩", "Fleisch & Wurst"),
    ("rind", "🥩", "Fleisch & Wurst"),
    ("steak", "🥩", "Fleisch & Wurst"),
    ("hackfleisch", "🥩", "Fleisch & Wurst"),
    ("gehacktes", "🥩", "Fleisch & Wurst"),
    ("bratwurst", "🌭", "Fleisch & Wurst"),
    ("wurst", "🥓", "Fleisch & Wurst"),
    ("würstchen", "🌭", "Fleisch & Wurst"),
    ("salami", "🥓", "Fleisch & Wurst"),
    ("schinken", "🥓", "Fleisch & Wurst"),
    ("speck", "🥓", "Fleisch & Wurst"),
    ("lamm", "🥩", "Fleisch & Wurst"),
    ("ente", "🦆", "Fleisch & Wurst"),
    // Fisch
    ("lachs", "🐟", "Fisch"),
    ("forelle", "🐟", "Fisch"),
    ("thunfisch", "🐟", "Fisch"),
    ("hering", "🐟", "Fisch"),
    ("matjes", "🐟", "Fisch"),
    ("garnele", "🦐", "Fisch"),
    ("shrimp", "🦐", "Fisch"),
    ("fischstäbchen", "🐟", "Tiefkühl"),
    ("fisch", "🐟", "Fisch"),
    // Backwaren
    ("brot", "🍞", "Backwaren"),
    ("brötchen", "🥐", "Backwaren"),
    ("baguette", "🥖", "Backwaren"),
    ("croissant", "🥐", "Backwaren"),
    ("toast", "🍞", "Backwaren"),
    ("kuchen", "🍰", "Backwaren"),
    ("torte", "🍰", "Backwaren"),
    // Tiefkühl
    ("tiefkühl", "❄️", "Tiefkühl"),
    ("tk-", "❄️", "Tiefkühl"),
    ("pizza", "🍕", "Tiefkühl"),
    ("pommes", "🍟", "Tiefkühl"),
    ("eiscreme", "🍨", "Tiefkühl"),
    ("eis am stiel", "🍦", "Tiefkühl"),
    ("langnese", "🍦", "Tiefkühl"),
    // Süßes & Snacks
    ("schokolade", "🍫", "Süßes & Snacks"),
    ("schoko", "🍫", "Süßes & Snacks"),
    ("praline", "🍫", "Süßes & Snacks"),
    ("bonbon", "🍬", "Süßes & Snacks"),
    ("gummibär", "🍬", "Süßes & Snacks"),
    ("fruchtgummi", "🍬", "Süßes & Snacks"),
    ("keks", "🍪", "Süßes & Snacks"),
    ("cookie", "🍪", "Süßes & Snacks"),
    ("chips", "🥔", "Süßes & Snacks"),
    ("erdnuss", "🥜", "Süßes & Snacks"),
    ("nüsse", "🥜", "Süßes & Snacks"),
    ("popcorn", "🍿", "Süßes & Snacks"),
    ("müsliriegel", "🍫", "Süßes & Snacks"),
    // Getränke
    ("wasser", "💧", "Getränke"),
    ("saft", "🧃", "Getränke"),
    ("schorle", "🧃", "Getränke"),
    ("apfelschorle", "🧃", "Getränke"),
    ("limonade", "🥤", "Getränke"),
    ("cola", "🥤", "Getränke"),
    ("eistee", "🥤", "Getränke"),
    ("energy", "⚡", "Getränke"),
    ("kaffee", "☕", "Getränke"),
    ("espresso", "☕", "Getränke"),
    ("tee", "🍵", "Getränke"),
    ("kakao", "🍫", "Getränke"),
    // Alkohol
    ("bier", "🍺", "Alkohol"),
    ("pils", "🍺", "Alkohol"),
    ("weizen", "🍺", "Alkohol"),
    ("wein", "🍷", "Alkohol"),
    ("sekt", "🥂", "Alkohol"),
    ("prosecco", "🥂", "Alkohol"),
    ("vodka", "🍸", "Alkohol"),
    ("wodka", "🍸", "Alkohol"),
    ("whisky", "🥃", "Alkohol"),
    ("rum", "🥃", "Alkohol"),
    ("gin", "🍸", "Alkohol"),
    ("likör", "🍸", "Alkohol"),
    // Vorräte & Kochen
    ("nudel", "🍝", "Vorräte & Kochen"),
    ("pasta", "🍝", "Vorräte & Kochen"),
    ("spaghetti", "🍝", "Vorräte & Kochen"),
    ("reis", "🍚", "Vorräte & Kochen"),
    ("mehl", "🌾", "Vorräte & Kochen"),
    ("zucker", "🍬", "Vorräte & Kochen"),
    ("salz", "🧂", "Vorräte & Kochen"),
    ("gewürz", "🧂", "Vorräte & Kochen"),
    ("öl", "🫒", "Vorräte & Kochen"),
    ("essig", "🫙", "Vorräte & Kochen"),
    ("ketchup", "🍅", "Vorräte & Kochen"),
    ("senf", "🌭", "Vorräte & Kochen"),
    ("mayonnaise", "🥪", "Vorräte & Kochen"),
    ("honig", "🍯", "Vorräte & Kochen"),
    ("marmelade", "🍓", "Vorräte & Kochen"),
    ("konfitüre", "🍓", "Vorräte & Kochen"),
    ("nutella", "🍫", "Vorräte & Kochen"),
    ("müsli", "🥣", "Vorräte & Kochen"),
    ("cornflakes", "🥣", "Vorräte & Kochen"),
    ("haferflocken", "🥣", "Vorräte & Kochen"),
    ("suppe", "🍲", "Vorräte & Kochen"),
    ("sauce", "🥫", "Vorräte & Kochen"),
    ("soße", "🥫", "Vorräte & Kochen"),
    ("konserve", "🥫", "Vorräte & Kochen"),
    ("dose", "🥫", "Vorräte & Kochen"),
    // Drogerie
    ("shampoo", "🧴", "Drogerie"),
    ("duschgel", "🧴", "Drogerie"),
    ("seife", "🧼", "Drogerie"),
    ("zahnpasta", "🪥", "Drogerie"),
    ("zahnbürste", "🪥", "Drogerie"),
    ("deo", "🧴", "Drogerie"),
    ("creme", "🧴", "Drogerie"),
    ("rasier", "🪒", "Drogerie"),
    ("taschentücher", "🤧", "Drogerie"),
    // Haushalt
    ("waschmittel", "🧴", "Haushalt"),
    ("spülmittel", "🧽", "Haushalt"),
    ("spülmaschine", "🧽", "Haushalt"),
    ("reiniger", "🧽", "Haushalt"),
    ("putzmittel", "🧽", "Haushalt"),
    ("toilettenpapier", "🧻", "Haushalt"),
    ("küchenrolle", "🧻", "Haushalt"),
    ("müllbeutel", "🗑️", "Haushalt"),
    ("batterie", "🔋", "Haushalt"),
    ("kerze", "🕯️", "Haushalt"),
    // Tierbedarf
    ("katzenfutter", "🐱", "Tierbedarf"),
    ("katzenmilch", "🐱", "Tierbedarf"),
    ("katzen", "🐱", "Tierbedarf"),
    ("hundefutter", "🐶", "Tierbedarf"),
    ("hunde", "🐶", "Tierbedarf"),
    ("tierfutter", "🐾", "Tierbedarf"),
    ("katzenstreu", "🐱", "Tierbedarf"),
    // Kinder
    ("windel", "👶", "Kinder"),
    ("babynahrung", "🍼", "Kinder"),
    ("babybrei", "🍼", "Kinder"),
    ("feuchttücher", "👶", "Kinder"),
    ("spielzeug", "🧸", "Kinder"),
    ("spielwaren", "🧸", "Kinder"),
    ("lego", "🧸", "Kinder"),
    ("playmobil", "🧸", "Kinder"),
    ("minecraft", "🧸", "Kinder"),
    ("poké", "🧸", "Kinder"),
    ("puppe", "🧸", "Kinder"),
    ("lupilu", "👶", "Kinder"),
    // Molkerei/Dessert-Zusätze
    ("monte", "🍮", "Molkerei & Eier"),
    ("pudding", "🍮", "Molkerei & Eier"),
    ("dessert", "🍮", "Molkerei & Eier"),
    ("mousse", "🍮", "Molkerei & Eier"),
    ("froop", "🥛", "Molkerei & Eier"),
    ("ehrmann", "🍮", "Molkerei & Eier"),
    ("ghurt", "🥛", "Molkerei & Eier"),
    // Vorräte-Zusätze
    ("fruchtaufstrich", "🍓", "Vorräte & Kochen"),
    ("aufstrich", "🫙", "Vorräte & Kochen"),
    ("tortilla", "🌯", "Vorräte & Kochen"),
    ("wrap", "🌯", "Vorräte & Kochen"),
    ("fertiggericht", "🍲", "Vorräte & Kochen"),
    ("noodle", "🍜", "Vorräte & Kochen"),
    ("knäcke", "🍘", "Vorräte & Kochen"),
    ("wasa", "🍘", "Vorräte & Kochen"),
    ("cracker", "🍘", "Süßes & Snacks"),
    ("granola", "🥣", "Vorräte & Kochen"),
    ("porridge", "🥣", "Vorräte & Kochen"),
    ("würzmisch", "🧂", "Vorräte & Kochen"),
    ("brühe", "🍲", "Vorräte & Kochen"),
    ("pesto", "🌿", "Vorräte & Kochen"),
    ("olive", "🫒", "Vorräte & Kochen"),
    ("antipasti", "🫒", "Vorräte & Kochen"),
    ("couscous", "🍚", "Vorräte & Kochen"),
    ("linsen", "🫘", "Vorräte & Kochen"),
    ("bohnen", "🫘", "Vorräte & Kochen"),
    ("kichererbse", "🫘", "Vorräte & Kochen"),
    ("lasagne", "🍝", "Vorräte & Kochen"),
    // Getränke-Zusätze
    ("drink", "🥤", "Getränke"),
    ("trinkmahlzeit", "🥤", "Getränke"),
    ("smoothie", "🧃", "Getränke"),
    ("volvic", "💧", "Getränke"),
    ("gerolsteiner", "💧", "Getränke"),
    ("nescaf", "☕", "Getränke"),
    ("dallmayr", "☕", "Getränke"),
    ("melitta", "☕", "Getränke"),
    ("tchibo", "☕", "Getränke"),
    ("cappuccino", "☕", "Getränke"),
    ("alpro", "🌱", "Getränke"),
    // Alkohol-Zusätze
    ("whiskey", "🥃", "Alkohol"),
    ("bourbon", "🥃", "Alkohol"),
    ("champagner", "🥂", "Alkohol"),
    ("secco", "🥂", "Alkohol"),
    ("aperitivo", "🍹", "Alkohol"),
    ("aperol", "🍹", "Alkohol"),
    ("weinbrand", "🥃", "Alkohol"),
    ("obstbrand", "🥃", "Alkohol"),
    ("korn", "🥃", "Alkohol"),
    ("radler", "🍺", "Alkohol"),
    ("weißwein", "🍷", "Alkohol"),
    ("rotwein", "🍷", "Alkohol"),
    ("roséwein", "🍷", "Alkohol"),
    ("rosé", "🍷", "Alkohol"),
    ("riesling", "🍷", "Alkohol"),
    ("primitivo", "🍷", "Alkohol"),
    ("grigio", "🍷", "Alkohol"),
    ("burgunder", "🍷", "Alkohol"),
    ("dornfelder", "🍷", "Alkohol"),
    ("merlot", "🍷", "Alkohol"),
    ("sauvignon", "🍷", "Alkohol"),
    ("tempranillo", "🍷", "Alkohol"),
    ("zweigelt", "🍷", "Alkohol"),
    ("chardonnay", "🍷", "Alkohol"),
    ("müller-thurgau", "🍷", "Alkohol"),
    ("cuvée", "🍷", "Alkohol"),
    ("winzer", "🍷", "Alkohol"),
    ("vino", "🍷", "Alkohol"),
    ("cimarosa", "🍷", "Alkohol"),
    ("trocken", "🍷", "Alkohol"),
    ("lieblich", "🍷", "Alkohol"),
    ("feinherb", "🍷", "Alkohol"),
    ("kingshill", "🥃", "Alkohol"),
    ("doppelkorn", "🥃", "Alkohol"),
    // Süßes-Zusätze (Marken)
    ("milka", "🍫", "Süßes & Snacks"),
    ("ferrero", "🍫", "Süßes & Snacks"),
    ("storck", "🍫", "Süßes & Snacks"),
    ("lindt", "🍫", "Süßes & Snacks"),
    ("merci", "🍫", "Süßes & Snacks"),
    ("toffifee", "🍫", "Süßes & Snacks"),
    ("duplo", "🍫", "Süßes & Snacks"),
    ("giotto", "🍫", "Süßes & Snacks"),
    ("yogurette", "🍫", "Süßes & Snacks"),
    ("dickmann", "🍫", "Süßes & Snacks"),
    ("riegel", "🍫", "Süßes & Snacks"),
    ("haribo", "🍬", "Süßes & Snacks"),
    ("kaugummi", "🍬", "Süßes & Snacks"),
    ("wrigley", "🍬", "Süßes & Snacks"),
    ("lakritz", "🍬", "Süßes & Snacks"),
    ("marshmallow", "🍬", "Süßes & Snacks"),
    ("mikado", "🍪", "Süßes & Snacks"),
    ("tuc", "🍪", "Süßes & Snacks"),
    ("waffel", "🧇", "Süßes & Snacks"),
    ("tiramisu", "🍰", "Süßes & Snacks"),
    ("mochi", "🍡", "Süßes & Snacks"),
    ("pom-bär", "🥔", "Süßes & Snacks"),
    ("trockenfrüchte", "🍇", "Süßes & Snacks"),
    ("studentenfutter", "🥜", "Süßes & Snacks"),
    // Tiefkühl-Zusätze
    ("eis", "🍦", "Tiefkühl"),
    ("stieleis", "🍦", "Tiefkühl"),
    ("eistüte", "🍦", "Tiefkühl"),
    ("iglo", "❄️", "Tiefkühl"),
    ("frosta", "❄️", "Tiefkühl"),
    ("tiefgefroren", "❄️", "Tiefkühl"),
    ("nugget", "🍗", "Tiefkühl"),
    // Fleisch-Zusätze
    ("mett", "🥩", "Fleisch & Wurst"),
    ("corned beef", "🥩", "Fleisch & Wurst"),
    ("frikadelle", "🍖", "Fleisch & Wurst"),
    ("burger", "🍔", "Fleisch & Wurst"),
    ("gyros", "🥙", "Fleisch & Wurst"),
    ("döner", "🥙", "Fleisch & Wurst"),
    ("geflügel", "🍗", "Fleisch & Wurst"),
    ("filet", "🥩", "Fleisch & Wurst"),
    // Obst/Gemüse-Zusätze
    ("zwetschge", "🟣", "Obst & Gemüse"),
    ("kohl", "🥬", "Obst & Gemüse"),
    ("beeren", "🫐", "Obst & Gemüse"),
    ("walnuss", "🥜", "Süßes & Snacks"),
    ("nuss", "🥜", "Süßes & Snacks"),
    ("pflanze", "🪴", "Sonstiges"),
    ("blume", "💐", "Sonstiges"),
    ("kräuter", "🌿", "Obst & Gemüse"),
    // Drogerie-Zusätze
    ("sebamed", "🧴", "Drogerie"),
    ("nivea", "🧴", "Drogerie"),
    ("dusche", "🚿", "Drogerie"),
    ("hygiene", "🧴", "Drogerie"),
    ("vitamin", "💊", "Drogerie"),
    ("pflaster", "🩹", "Drogerie"),
    ("tampon", "🩹", "Drogerie"),
    // Haushalt-Zusätze
    ("zewa", "🧻", "Haushalt"),
    ("küchentücher", "🧻", "Haushalt"),
    ("swiffer", "🧽", "Haushalt"),
    ("fleckentferner", "🧴", "Haushalt"),
    ("vanish", "🧴", "Haushalt"),
    ("entkalker", "🧽", "Haushalt"),
    ("weichspüler", "🧴", "Haushalt"),
    ("wc", "🚽", "Haushalt"),
    ("geschirr", "🍽️", "Haushalt"),
    ("pfanne", "🍳", "Haushalt"),
    ("topf", "🍳", "Haushalt"),
    ("bräter", "🍳", "Haushalt"),
    ("messer", "🔪", "Haushalt"),
    ("maschine", "🔌", "Haushalt"),
    ("staubsauger", "🧹", "Haushalt"),
    ("bügel", "🧺", "Haushalt"),
    ("vileda", "🧽", "Haushalt"),
    ("kochtopf", "🍳", "Haushalt"),
    ("knorr", "🍲", "Vorräte & Kochen"),
    ("patros", "🧀", "Molkerei & Eier"),
    ("stitch", "🧸", "Kinder"),
    // NonFood → Sonstiges
    ("parkside", "🛠️", "Sonstiges"),
    ("bohr", "🛠️", "Sonstiges"),
    ("werkzeug", "🛠️", "Sonstiges"),
    ("rasenmäher", "🛠️", "Sonstiges"),
    ("akku", "🔋", "Sonstiges"),
    ("livarno", "🛋️", "Sonstiges"),
    ("silvercrest", "🔌", "Sonstiges"),
    ("tronic", "🔌", "Sonstiges"),
    ("elektro", "🔌", "Sonstiges"),
    ("fernseher", "📺", "Sonstiges"),
    ("kopfhörer", "🎧", "Sonstiges"),
    ("esmara", "👕", "Sonstiges"),
    ("crivit", "🎽", "Sonstiges"),
    ("shirt", "👕", "Sonstiges"),
    ("hoodie", "👕", "Sonstiges"),
    ("pullover", "👕", "Sonstiges"),
    ("jacke", "🧥", "Sonstiges"),
    ("hose", "👖", "Sonstiges"),
    ("shorts", "🩳", "Sonstiges"),
    ("jeans", "👖", "Sonstiges"),
    ("socken", "🧦", "Sonstiges"),
    ("slip", "🩲", "Sonstiges"),
    ("sneaker", "👟", "Sonstiges"),
    ("schuh", "👟", "Sonstiges"),
    ("bettwäsche", "🛏️", "Sonstiges"),
    ("kissen", "🛏️", "Sonstiges"),
    ("decke", "🛏️", "Sonstiges"),
    ("matratze", "🛏️", "Sonstiges"),
    ("teppich", "🛋️", "Sonstiges"),
    ("leuchte", "💡", "Sonstiges"),
    ("lampe", "💡", "Sonstiges"),
    ("lichterkette", "💡", "Sonstiges"),
    ("ventilator", "🌀", "Sonstiges"),
    ("koffer", "🧳", "Sonstiges"),
    ("tasche", "🧳", "Sonstiges"),
    ("rucksack", "🎒", "Sonstiges"),
    ("wenger", "🧳", "Sonstiges"),
    ("ultimate speed", "🚗", "Sonstiges"),
    ("auto", "🚗", "Sonstiges"),
    ("fahrrad", "🚲", "Sonstiges"),
    ("garten", "🪴", "Sonstiges"),
    ("vegan", "🌱", "Sonstiges"),
    ("tofu", "🌱", "Sonstiges"),
    ("soja", "🌱", "Sonstiges"),
    ("soya", "🌱", "Sonstiges"),
    // Runde 4: Long-Tail aus echten Daten
    ("ice tea", "🥤", "Getränke"),
    ("capri-sun", "🧃", "Getränke"),
    ("säfte", "🧃", "Getränke"),
    ("nektar", "🧃", "Getränke"),
    ("brause", "🥤", "Getränke"),
    ("ayran", "🥛", "Getränke"),
    ("schwarztee", "🍵", "Getränke"),
    ("früchtetee", "🍵", "Getränke"),
    ("kräutertee", "🍵", "Getränke"),
    ("lichtenauer", "💧", "Getränke"),
    ("adelholzener", "💧", "Getränke"),
    ("water", "💧", "Getränke"),
    ("limoncello", "🍸", "Alkohol"),
    ("spritz", "🍹", "Alkohol"),
    ("edelbrand", "🥃", "Alkohol"),
    ("amaro", "🍸", "Alkohol"),
    ("smirnoff", "🍸", "Alkohol"),
    ("qualitätswein", "🍷", "Alkohol"),
    ("rebsortenwein", "🍷", "Alkohol"),
    ("bräu", "🍺", "Alkohol"),
    ("weißbier", "🍺", "Alkohol"),
    ("camembert", "🧀", "Molkerei & Eier"),
    ("cheddar", "🧀", "Molkerei & Eier"),
    ("hochland", "🧀", "Molkerei & Eier"),
    ("hirtenkäse", "🧀", "Molkerei & Eier"),
    ("rama", "🧈", "Molkerei & Eier"),
    ("streichzart", "🧈", "Molkerei & Eier"),
    ("gustavo", "🍕", "Tiefkühl"),
    ("hörnchen", "🍦", "Tiefkühl"),
    ("ice", "🍦", "Tiefkühl"),
    ("dip", "🫙", "Vorräte & Kochen"),
    ("remoulade", "🫙", "Vorräte & Kochen"),
    ("homann", "🫙", "Vorräte & Kochen"),
    ("cashew", "🥜", "Süßes & Snacks"),
    ("macadamia", "🥜", "Süßes & Snacks"),
    ("pinienkerne", "🥜", "Vorräte & Kochen"),
    ("mandel", "🥜", "Süßes & Snacks"),
    ("frucht", "🍓", "Obst & Gemüse"),
    ("früchte", "🍓", "Obst & Gemüse"),
    ("sülze", "🥩", "Fleisch & Wurst"),
    ("cevapcici", "🥩", "Fleisch & Wurst"),
    ("kabanossi", "🥓", "Fleisch & Wurst"),
    ("krakauer", "🥓", "Fleisch & Wurst"),
    ("wachtel", "🍗", "Fleisch & Wurst"),
    ("spanferkel", "🥩", "Fleisch & Wurst"),
    ("braten", "🥩", "Fleisch & Wurst"),
    ("knoppers", "🍫", "Süßes & Snacks"),
    ("leibniz", "🍪", "Süßes & Snacks"),
    ("celebrations", "🍫", "Süßes & Snacks"),
    ("mars", "🍫", "Süßes & Snacks"),
    ("tafel", "🍫", "Süßes & Snacks"),
    ("lambertz", "🍪", "Süßes & Snacks"),
    ("gebäck", "🍪", "Süßes & Snacks"),
    ("törtchen", "🧁", "Süßes & Snacks"),
    ("laugen", "🥨", "Backwaren"),
    ("brezel", "🥨", "Backwaren"),
    ("gillette", "🪒", "Drogerie"),
    ("odol", "🪥", "Drogerie"),
    ("mundspül", "🪥", "Drogerie"),
    ("scholl", "🦶", "Drogerie"),
    ("hornhaut", "🦶", "Drogerie"),
    ("haarbürste", "🧴", "Drogerie"),
    ("kamm", "🧴", "Drogerie"),
    ("lenor", "🧴", "Haushalt"),
    ("spee", "🧴", "Haushalt"),
    ("fairy", "🧽", "Haushalt"),
    ("airwick", "🌸", "Haushalt"),
    ("wäsche", "🧺", "Haushalt"),
    ("küchen", "🍽️", "Haushalt"),
    ("gläser", "🥂", "Haushalt"),
    ("löffel", "🥄", "Haushalt"),
    ("fritteuse", "🍳", "Haushalt"),
    ("bürste", "🧹", "Haushalt"),
    ("bodenkehrer", "🧹", "Haushalt"),
    ("geschenkpapier", "🎁", "Haushalt"),
    ("aufbewahrung", "📦", "Haushalt"),
    ("feuerlöscher", "🧯", "Sonstiges"),
    ("schlafsack", "🛏️", "Sonstiges"),
    ("werkstatt", "🛠️", "Sonstiges"),
    ("blutdruck", "🩺", "Sonstiges"),
    ("lesehilfe", "👓", "Sonstiges"),
    ("brille", "👓", "Sonstiges"),
    ("guthabenkarte", "💳", "Sonstiges"),
    ("kreuzworträtsel", "📚", "Sonstiges"),
    ("playtive", "🧸", "Kinder"),
    ("hot wheels", "🧸", "Kinder"),
    ("plüsch", "🧸", "Kinder"),
    ("funko", "🧸", "Kinder"),
    ("schreibwaren", "✏️", "Kinder"),
    ("kugelschreiber", "✏️", "Kinder"),
    ("whiskas", "🐱", "Tierbedarf"),
    ("dreamies", "🐱", "Tierbedarf"),
    ("sheba", "🐱", "Tierbedarf"),
    ("felix", "🐱", "Tierbedarf"),
    ("pedigree", "🐶", "Tierbedarf"),
    // Runde 5: Long-Tail aus echten Daten
    ("weißkohl", "🥬", "Obst & Gemüse"),
    ("spitzkohl", "🥬", "Obst & Gemüse"),
    ("rotkohl", "🥬", "Obst & Gemüse"),
    ("grünkohl", "🥬", "Obst & Gemüse"),
    ("broccoli", "🥦", "Obst & Gemüse"),
    ("pfifferling", "🍄", "Obst & Gemüse"),
    ("pistazie", "🥜", "Süßes & Snacks"),
    ("chrysantheme", "💐", "Sonstiges"),
    ("dahlie", "💐", "Sonstiges"),
    ("bacon", "🥓", "Fleisch & Wurst"),
    ("lyoner", "🥓", "Fleisch & Wurst"),
    ("prosciutto", "🥓", "Fleisch & Wurst"),
    ("chipolata", "🥓", "Fleisch & Wurst"),
    ("haxe", "🥩", "Fleisch & Wurst"),
    ("kaninchen", "🥩", "Fleisch & Wurst"),
    ("wiener", "🌭", "Fleisch & Wurst"),
    ("grillfackel", "🥩", "Fleisch & Wurst"),
    ("ribs", "🍖", "Fleisch & Wurst"),
    ("wings", "🍗", "Fleisch & Wurst"),
    ("kotelett", "🥩", "Fleisch & Wurst"),
    ("mehrkornbrot", "🍞", "Backwaren"),
    ("bauernbrot", "🍞", "Backwaren"),
    ("steinofenbrot", "🍞", "Backwaren"),
    ("ofenbrot", "🍞", "Backwaren"),
    ("knusperbrot", "🍘", "Backwaren"),
    ("vollkornbrot", "🍞", "Backwaren"),
    ("blätterteig", "🥐", "Backwaren"),
    ("eintopf", "🍲", "Vorräte & Kochen"),
    ("gnocchi", "🍝", "Vorräte & Kochen"),
    ("barilla", "🍝", "Vorräte & Kochen"),
    ("ajvar", "🫙", "Vorräte & Kochen"),
    ("miracel whip", "🫙", "Vorräte & Kochen"),
    ("expressreis", "🍚", "Vorräte & Kochen"),
    ("ben’s", "🍚", "Vorräte & Kochen"),
    ("ben's", "🍚", "Vorräte & Kochen"),
    ("piccolini", "🍕", "Tiefkühl"),
    ("wagner", "🍕", "Tiefkühl"),
    ("pirulo", "🍦", "Tiefkühl"),
    ("brownie", "🍫", "Süßes & Snacks"),
    ("doppelkeks", "🍪", "Süßes & Snacks"),
    ("prinzen", "🍪", "Süßes & Snacks"),
    ("hobbits", "🍪", "Süßes & Snacks"),
    ("brandt", "🍪", "Süßes & Snacks"),
    ("hitschies", "🍬", "Süßes & Snacks"),
    ("bueno", "🍫", "Süßes & Snacks"),
    ("pingui", "🍫", "Süßes & Snacks"),
    ("kinder country", "🍫", "Süßes & Snacks"),
    ("kinder tris", "🍫", "Süßes & Snacks"),
    ("lorenz", "🥔", "Süßes & Snacks"),
    ("kaba", "🍫", "Getränke"),
    ("jacobs", "☕", "Getränke"),
    ("senseo", "☕", "Getränke"),
    ("caffè crema", "☕", "Getränke"),
    ("pepsi", "🥤", "Getränke"),
    ("schweppes", "🥤", "Getränke"),
    ("schwip schwap", "🥤", "Getränke"),
    ("limo", "🥤", "Getränke"),
    ("granini", "🧃", "Getränke"),
    ("naturelle", "💧", "Getränke"),
    ("budweiser", "🍺", "Alkohol"),
    ("budvar", "🍺", "Alkohol"),
    ("benediktiner", "🍺", "Alkohol"),
    ("lübzer", "🍺", "Alkohol"),
    ("cinzano", "🥂", "Alkohol"),
    ("asti", "🥂", "Alkohol"),
    ("lillet", "🍹", "Alkohol"),
    ("goldkrone", "🥃", "Alkohol"),
    ("grappa", "🥃", "Alkohol"),
    ("géramont", "🧀", "Molkerei & Eier"),
    ("maasdamer", "🧀", "Molkerei & Eier"),
    ("arla", "🧈", "Molkerei & Eier"),
    ("ariel", "🧴", "Haushalt"),
    ("kuschelweich", "🧴", "Haushalt"),
    ("reinigungstücher", "🧻", "Haushalt"),
    ("frischhaltedose", "📦", "Haushalt"),
    ("schüssel", "🥣", "Haushalt"),
    ("schneidebrett", "🔪", "Haushalt"),
    ("backform", "🍳", "Haushalt"),
    ("auflauf", "🍳", "Haushalt"),
    ("kontaktgrill", "🍳", "Haushalt"),
    ("mixer", "🔌", "Haushalt"),
    ("sandwichmaker", "🍳", "Haushalt"),
    ("karaffe", "🥂", "Haushalt"),
    ("sodastream", "🫧", "Haushalt"),
    ("spül", "🧽", "Haushalt"),
    ("regal", "🗄️", "Sonstiges"),
    ("wecker", "⏰", "Sonstiges"),
    ("geschenkkarte", "💳", "Sonstiges"),
    ("gutscheinkarte", "💳", "Sonstiges"),
    ("trinkflasche", "🍶", "Sonstiges"),
    ("bastelset", "🎨", "Kinder"),
    ("radierer", "✏️", "Kinder"),
    ("überraschung", "🧸", "Kinder"),
    ("autan", "🦟", "Drogerie"),
    ("bebe", "🧴", "Drogerie"),
    ("trimmer", "🪒", "Drogerie"),
    ("lockenstab", "💇", "Drogerie"),
    // Runde 6: Long-Tail aus echten Daten
    ("fleisch", "🥩", "Fleisch & Wurst"),
    ("serrano", "🥓", "Fleisch & Wurst"),
    ("chicken", "🍗", "Fleisch & Wurst"),
    ("activia", "🥛", "Molkerei & Eier"),
    ("actimel", "🥛", "Molkerei & Eier"),
    ("danone", "🥛", "Molkerei & Eier"),
    ("babybel", "🧀", "Molkerei & Eier"),
    ("mascarpone", "🧀", "Molkerei & Eier"),
    ("grana padano", "🧀", "Molkerei & Eier"),
    ("scamorza", "🧀", "Molkerei & Eier"),
    ("becel", "🧈", "Molkerei & Eier"),
    ("dinkel", "🌾", "Vorräte & Kochen"),
    ("flocken", "🥣", "Vorräte & Kochen"),
    ("kühne", "🫙", "Vorräte & Kochen"),
    ("balsamico", "🫙", "Vorräte & Kochen"),
    ("kathi", "🍰", "Vorräte & Kochen"),
    ("sherry", "🍷", "Alkohol"),
    ("bordeaux", "🍷", "Alkohol"),
    ("chianti", "🍷", "Alkohol"),
    ("amaretto", "🍸", "Alkohol"),
    ("ouzo", "🥃", "Alkohol"),
    ("metaxa", "🥃", "Alkohol"),
    ("akvavit", "🥃", "Alkohol"),
    ("spirituosen", "🥃", "Alkohol"),
    ("lagerbier", "🍺", "Alkohol"),
    ("vitamalz", "🥤", "Getränke"),
    ("fanta", "🥤", "Getränke"),
    ("sprite", "🥤", "Getränke"),
    ("mezzo mix", "🥤", "Getränke"),
    ("grapefruit", "🍊", "Obst & Gemüse"),
    ("nimm2", "🍬", "Süßes & Snacks"),
    ("lachgummi", "🍬", "Süßes & Snacks"),
    ("muffin", "🧁", "Süßes & Snacks"),
    ("grissini", "🥖", "Süßes & Snacks"),
    ("taft", "💇", "Drogerie"),
    ("haar", "💇", "Drogerie"),
    ("axe", "🧴", "Drogerie"),
    ("softlan", "🧴", "Haushalt"),
    ("weißer riese", "🧴", "Haushalt"),
    ("biff", "🧽", "Haushalt"),
    ("haushaltstücher", "🧻", "Haushalt"),
    ("handtuch", "🧺", "Haushalt"),
    ("trinkhalm", "🥤", "Haushalt"),
    ("zahnstocher", "🍴", "Haushalt"),
    ("hammer", "🛠️", "Sonstiges"),
    ("heimwerk", "🛠️", "Sonstiges"),
    ("kajak", "🛶", "Sonstiges"),
    ("sofa", "🛋️", "Sonstiges"),
    ("hemd", "👕", "Sonstiges"),
    ("dorade", "🐟", "Fisch"),
    ("calamares", "🦑", "Fisch"),
    ("sandwich", "🥪", "Sonstiges"),
    ("snackbox", "🥪", "Sonstiges"),
    ("spiel", "🧸", "Kinder"),
    // "filet" (Fleisch) und "lachs" sind gleich lang — Compounds explizit,
    // sonst entscheidet bei Gleichstand die Tabellenreihenfolge
    ("lachsfilet", "🐟", "Fisch"),
    ("fischfilet", "🐟", "Fisch"),
    ("forellenfilet", "🐟", "Fisch"),
    ("seelachs", "🐟", "Fisch"),
    ("zaziki", "🥣", "Molkerei & Eier"),
    ("tzatziki", "🥣", "Molkerei & Eier"),
];

/// Substring-Match; kurze Keywords (≤ 4 Bytes) müssen am Wortanfang stehen,
/// sonst träfe "eis" auch "Preis" und "reis" auch "Preise".
fn keyword_matches(hay: &str, kw: &str) -> bool {
    if kw.len() > 4 {
        return hay.contains(kw);
    }
    let mut from = 0;
    while let Some(pos) = hay[from..].find(kw) {
        let abs = from + pos;
        if abs == 0 || !hay[..abs].chars().next_back().is_some_and(|c| c.is_alphabetic()) {
            return true;
        }
        from = abs + kw.len();
    }
    false
}

/// Rohkategorie eines Scrapers → normalisierte Kategorie, wenn eindeutig.
fn map_raw_category(raw: &str) -> Option<&'static str> {
    let r = raw.to_lowercase();
    if r == "eis" {
        // exakt, sonst träfe "eis" auch "Fleisch"
        return Some("Tiefkühl");
    }
    let table: &[(&[&str], &str)] = &[
        // vor der Alkohol-Zeile: "Alkoholfreie Weine & Biere" sind Getränke
        (&["alkoholfrei"], "Getränke"),
        // vor der Obst-Zeile, sonst fiele "Obstbrand" unter Obst & Gemüse
        (&["obstbrand", "weinbrand"], "Alkohol"),
        (&["obst", "gemüse", "gemuese"], "Obst & Gemüse"),
        (&["molkerei", "käse", "milchprodukt", "joghurt"], "Molkerei & Eier"),
        (&["fleisch", "wurst", "geflügel"], "Fleisch & Wurst"),
        (&["fisch"], "Fisch"),
        (&["backware", "bäckerei", "brot"], "Backwaren"),
        (&["tiefkühl", "tiefkuehl", "tk "], "Tiefkühl"),
        (&["süß", "suess", "snack", "knabber", "keks"], "Süßes & Snacks"),
        (&["getränk", "getraenk", "kaffee", "tee"], "Getränke"),
        (
            &[
                "bier", "wein", "spirituosen", "alkohol", "whisk", "likör", "korn", "wodka",
                "rum", "gin", "obstbrand", "champagner", "sekt", "schaumwein", "cocktail",
                "aperitif",
            ],
            "Alkohol",
        ),
        (&["vorrat", "vorräte", "grundnahrung", "nährmittel", "kochen", "frühstück", "konserve", "feinkost"], "Vorräte & Kochen"),
        (&["drogerie", "pflege", "kosmetik", "gesundheit"], "Drogerie"),
        (&["haushalt", "reinigung", "wasch"], "Haushalt"),
        (&["tiernahrung", "tierfutter", "tierbedarf", "haustier"], "Tierbedarf"),
        (&["baby", "kind", "schul"], "Kinder"),
    ];
    table
        .iter()
        .find(|(keys, _)| keys.iter().any(|k| r.contains(k)))
        .map(|(_, cat)| *cat)
}

#[derive(Debug, Clone, PartialEq)]
pub struct Enrichment {
    pub category: &'static str,
    pub emoji: &'static str,
    /// true, wenn das Emoji nur der Kategorie-Fallback ist (kein Keyword-Treffer).
    pub emoji_is_fallback: bool,
}

/// Titel/Untertitel/Rohkategorie → Kategorie + Emoji.
pub fn enrich(title: &str, subtitle: Option<&str>, raw_category: Option<&str>) -> Enrichment {
    // Weiches Trennzeichen (U+00AD) entfernen — Scraper-Titel wie
    // "Fertig­gericht" enthalten es mitten im Wort und brechen sonst den Match.
    let hay = format!("{} {}", title, subtitle.unwrap_or(""))
        .to_lowercase()
        .replace('\u{ad}', "");

    // Längstes passendes Keyword gewinnt ("kinderschokolade" → Schokolade,
    // nicht Kinder; "katzenmilch" → Katzen, nicht Milch).
    let find_best = |text: &str| {
        RULES
            .iter()
            .filter(|(kw, _, _)| keyword_matches(text, kw))
            .max_by_key(|(kw, _, _)| kw.len())
    };
    // Erst Titel+Untertitel; ohne Treffer die Rohkategorie ("Sekt &
    // Schaumwein", "Pflanzen", "Eis" …) als zweite Keyword-Quelle.
    let best = find_best(&hay).or_else(|| {
        raw_category.and_then(|raw| find_best(&raw.to_lowercase().replace('-', " ")))
    });

    let category = raw_category
        .and_then(map_raw_category)
        .or(best.map(|(_, _, c)| *c))
        .unwrap_or(FALLBACK_CATEGORY);

    match best {
        Some((_, emoji, _)) => Enrichment { category, emoji, emoji_is_fallback: false },
        None => Enrichment { category, emoji: default_emoji(category), emoji_is_fallback: true },
    }
}
